### ISSUE TITLE
can't get passed verification on Linux

### ISSUE THREAD

**Issue by StarMusa88** [lencx/ChatGPT#1290]
Hi, 

I can't seem to get past verification. It's been going on for these past few days.

![Screenshot_2024-05-20_21-54-25](https://github.com/lencx/ChatGPT/assets/142222631/6e7e318d-4074-4489-b98b-bea169f6c08d)
![Screenshot_2024-05-20_21-55-46](https://github.com/lencx/ChatGPT/assets/142222631/c6d88a09-4ce9-4f1a-862e-4e6c6e139505)

**Comment by StephenMal** [comment]
I seem to be having the same problem, version 1.1.0, Linux Debian PopOS.  Strangely works on my laptop with the same os.  I had similar issues when signing in before due to google's multi-step auth however refreshing the page worked, cannot refresh this page via ctrl-R nor by clicking view -> Refresh The Screen

**Comment by StephenMal** [comment]
@StarMusa88 I found installing the .deb allowed me to proceed past the cloudflare verification, whereas the docker image did not.  Hope that helps!

**Comment by StarMusa88** [comment]
> @StephenMal I'm actually running .deb and still can't get passed verification.  But when I run Chat-GPT from firefox browser everything works fine.
![Screenshot_2024-05-21_19-48-19](https://github.com/lencx/ChatGPT/assets/142222631/914aa815-8891-41dd-8e6d-b6e779bc71f5)

**Comment by StarMusa88** [comment]
After some testing on different distros Kali and Ubuntu. Issues are only with Kali linux.

**Comment by StarMusa88** [comment]
found a work around using chromium instead
