### ISSUE TITLE
[Bug] Stuck at cloudflare check.

### ISSUE THREAD

**Issue by irthomasthomas** [lencx/ChatGPT#179]
### Version

0.8.0

### Bug description

Using latest Appimage on fedora 37.
I can use the website through a browser fine. Firefox and chrome both work. But this app gets stuck at the cloudflare check. I tried changing the user agent to match the one I use in chrome, but that did not fix anything.

### OS

Fedora 37

### Environment

I would try building from source but I notice that VS Code is a requirement. Can I build it with VSCodium or Code OSS?

**Comment by lencx** [comment]
It does not require a specific code editor, rust and node.js environments are required.

**Comment by irthomasthomas** [comment]
I see, I'll try to build it then. Just the build instructions on the readme say to pre-install vscode and some extension: https://github.com/lencx/ChatGPT#how-do-i-build-it

 I'm in UK. And the site works fine in other browsers.

**Comment by lencx** [comment]
tauri is calling the system's built-in browser, and I can't be sure what detection mechanism openai is.

**Comment by irthomasthomas** [comment]
Do you mean the default browser? So that if I change the default browser setting on my system it will change for this?

**Comment by lencx** [comment]
I'm not sure, you can try (I don't think it has anything to do with the computer's settings).

**Comment by irthomasthomas** [comment]
> tauri is calling the system's built-in browser, and I can't be sure what detection mechanism openai is.

I'm on kde, so QTWebkit? There must be a reason they are treating you different to other clients. Let me know if there's something I can do to help you diagnose it.

**Comment by tk103331** [comment]
https://tauri.app/v1/references/webview-versions

**Comment by Manamama** [comment]
Re: 
`Cloudflare is a network problem, this problem is very frequent in China, many people have feedback on this problem,`
Interesting. AFAIK, also they are bound to apply AI network filtering (mandated by the US government, for starters), as per OpenAI's ToUs, see [my comment there](https://github.com/lencx/ChatGPT/issues/161#issuecomment-1374819519) or read them directly there.

**Comment by MrJarnould** [comment]
I am also stuck on the Cloudflare check.
@irthomasthomas did you manage to fix this problem?

**Comment by Manamama** [comment]
FYI, it has been working for me, almost always, for the past +2 weeks, better than in the "bare" browser, even despite intermittent: 
`Due to high demand on our systems, previous conversations are temporarily unavailable`
EU here: I half suspect they implemented regional throttling, partly as per their ToUs, see above. 

In short, in my EU country now @lencx 's tool is more reliable than the non-API direct access.

**Comment by Manamama** [comment]
As an (not topical) aside : the newest GPTChat (directly at backend) feature "stop generating" is a godsend. 

It saves generation tokens and patience: win-win situation.
