### ISSUE TITLE
[Feature] Plus Subscriber Login Link

### ISSUE THREAD

**Issue by kennyparsons** [lencx/ChatGPT#331]
### Feature description

ChatGPT just released the subscriber login link. Since they are constantly at capacity, they have introduced an email login link. You fill in your email and it emails you the direct login link (valid for 10 minutes). We need a feature to paste this login link into the standalone app, otherwise the login link just uses the default browser. 

### Motivation

Currently cannot use, due to constant capacity limits.

**Comment by FoxInTheB0xFFF** [comment]
+1

**Comment by Manamama** [comment]
Can somebody screenshot it and show how it works for them? I have been using OpenAI since SEP 2022 (sic) and have signed up twice or thrice for their "premium" subscriber/waiting list, in mid-JAN 2023 first, if only just to see what's like, but I have not seen any "live" link  yet, nor received any reply from that waiting list engine. 

Other related news, here is Bing and their "ChatGPT waiting list" as of today:
![Screenshot from 2023-02-08 09-56-01](https://user-images.githubusercontent.com/78492008/217484803-acdf8339-e5c1-4039-a103-d6b6f27b4cf0.png)

with gamification:
![Screenshot from 2023-02-08 09-58-34](https://user-images.githubusercontent.com/78492008/217484876-c0ba72bd-939f-4307-b8c5-e7da857f99be.png)
See also the industry news. 

-> Does the former work for anybody?

**Comment by WookedWare** [comment]
All it does is email you a link to the login page with a token attached:

https://chat.openai.com/auth/login?token=<token>

The problem is that when we click that link it opens in our default browser. I don't know rust so I didn't really dive into how your application works, but it seems like you are using an internal web browser to show chat gpt. We need a way to have that internal browser bring us to the login page, let us log in, and return to the main page of your application.

**Comment by mysticaltech** [comment]
Having the exact same issue!

**Comment by Romboter** [comment]
Current workaround is as follows, in the control center add the emailed link to the awesome dashboard list, then under settings>main window select the login link on the switch origin box and submit.

After the program restarts you will be prompted to login to your plus :)

**Comment by huyz** [comment]
@Romboter  thanks for the tip, but I'm getting "Oops! Script execution time exceeeded". Any idea?

**Comment by MohamedElashri** [comment]
> @Romboter thanks for the tip, but I'm getting "Oops! Script execution time exceeeded". Any idea?

ChatGPT is down now 
https://status.openai.com/

**Comment by huyz** [comment]
@MohamedElashri  Thanks. How much to pay for ChatGPT Pro and Ultra?

**Comment by MohamedElashri** [comment]
> 

There are only two tiers for ChatGPT now. Free and Plus (which costs $20 per month)
