### ISSUE TITLE
[Feature] Hitting 'Return' ('Enter') creates a new line instead of sending the message. 

### ISSUE THREAD

**Issue by rablinz** [lencx/ChatGPT#726]
### Feature description

In order to send a question that contains multiple lines, that I want spaced; I have to first compose my question in Notepad++ and copy and paste into the ChatGPT app. It would be very helpful to be able to use, or have the option to use, 'Enter', just like in any text editor, to create a new line and then click on the send button to send.

### Motivation

I mainly use ChatGPT to assist in writing code. Either composing an intitial question, or composing a response to a response from ChatGPT, requires code blocks seperated by new lines.

### Alternatives

having a check box near the text input box that indicates whether to use 'Enter' to send messages or to make a new line

**Comment by Betzalel-Maor** [comment]
You can just press <kbd>Shift</kbd> + <kbd>Enter</kbd> to create a new line. We want sending messages to the chat be fast and simple, not having to move the mouse to the send button every time.

**Comment by rablinz** [comment]
@Betzalel-Maor , even better. Great, thank you.

**Comment by DetlefSchmitt** [comment]
Shift + Enter is not a good solution for everybody. When I am busy working with ChatGPT I constantly forget that I have to use Shift+Enter to get a new line. Many times I have sent off incomplete questions. It is annoying! I wish there would be a preference setting to select a different option.

I understand your intention.  In casual conversation, you want to be fast and simple. However, if one uses ChatGPT e.g. as a programming assistant then it is better if one has a safety hurdle that prevents one from sending off a prompt prematurely. 

In addition, on many social media platforms carriage return is used to get a new line. Or one has the option to set it this way. So, people are used to it. Therefore, I support at least a preference option where one can choose how to send off a prompt.

**Comment by rablinz** [comment]
why was this closed? I wasn't aware of the shift + enter option, so that was still very helpful, but I think my suggested enhancements would still be an improvement

**Comment by blockbabak** [comment]
So, any news on this feature? Why not write a Chrom/Edge add-on/extension to deal with it?
This seems to be a problem with the PC WhatsApp module as well.
I am surprised that no one hasn't already done one,

**Comment by AlexanderTsarapkine** [comment]
Was this implemented? 
When I hit enter it creates a new line and I find it really jarring, if anything could you create a setting to make both sides happy since like @DetlefSchmitt mentioned, its awkward (atleast for me) having to move my mouse to create a new line especially when chatGPT behaves like a message service where hitting "Enter" is generally speaking the norm for sending a message.

**Comment by AlexanderTsarapkine** [comment]
Was this implemented? (it seems like it has?)
Could this be made an option for the user to choose as originally mentioned as an alternative. I am really not a fan of having to move my mouse every time I want to send a prompt through and much prefer the "Shift + Enter" creating the new line instead.

**Comment by sickdyd** [comment]
I use ChatGPT daily and I often accidentally hit return and send an incomplete requests. Please add the option to disable send on return.

It would be nice if you could use `cmd + return` to actually send it instead of plain return.

**Comment by rezelute** [comment]
I am finding this such a pain not having this feature! You mentioned above "We want sending messages to the chat be fast and simple" and I would say two things to this:
1. You are wasting bandwidth by people who keep accidentally pressing enter which then submits the request
2. Its not fast for a large number of users who are used to it being Enter creates a new line

This is a feature request to have the ability to toggle it like Slack has ...

**Comment by Betzalel-Maor** [comment]
> I am finding this such a pain not having this feature! You mentioned above "We want sending messages to the chat be fast and simple" and I would say two things to this:
> 
> 1. You are wasting bandwidth by people who keep accidentally pressing enter which then submits the request
> 2. Its not fast for a large number of users who are used to it being Enter creates a new line
> 
> This is a feature request to have the ability to toggle it like Slack has ...

Hi, so I actually agree with [DetlefSchmitt](https://github.com/DetlefSchmitt)'s suggestion above - to have a preference whether `Enter` functions as a new line or a quick send-message.

I completely understand how accidently hitting `Enter` can disrupt long and hard workflow, yet also consuming time for quick gpt-chatters.

**Comment by blockbabak** [comment]
Why are they making such a big deal out of this? 
Why are people who have designed an Artificial Intelligence system behaving like obtuse mules?
They are supposed to have access to the best talents in software. Maybe this is some sick psychological test, and they are grading us users for some idiotic index requested by DARPA.
The spooky issue is that it is not just ChatGPT, Gemini and Claude AI have the same setup.
Who could stop something that could gain competitive advantage over the others except the government.
This is how conspiracy theories start, isn't it?
If they would explain the reason, then at least there could be varying opinions on the matter and a discussion could be created. But there isn't. That makes it even more spooky.
Now what if this comment disappears? That would make it even more spooky. So please send confirmation while it is still visible for the next few days. If it doesn't go anywhere then fair enough, I don't need to be that paranoid.
There is simply no reason for not correcting such an obvious design flaw, is there?
I mean the current keyboard layout was born out of historical practices. When typewriters came along the layout was to prevent mechanical wear and tear of most used characters and typists around the world gained muscle memory on the basis of this decision. So, when electronic keyboards came up the layout was kept because people were used to it. That prevented interruption.
So, if those people saw the evolution of the logic so effectively why these Buffins with their Artificial Intelligence black boxes can't see it or even just copy it? 
Can someone please point out what I am not seeing here because by now everyone else must have seen it except us few.

**Comment by cercxtrova** [comment]
The funniest/most annoying thing is that when writing a message, you have to press shift+enter to go to the next line. But once you’ve made a mistake and accidentally sent an incomplete message, when you edit it, you don’t need to press shift+enter to go to the next line—just enter. Why is the behaviour different when editing? Because you know we edit it probably because of the "new line issue"? So why not just add the option? I’d like to have an option like on ClickUp, where by default you need to press shift+enter, but you can enable a setting so that enter creates a new line, and cmd+enter sends the message.
