### ISSUE TITLE
verify you are human

### ISSUE THREAD

**Issue by nitgo-latte** [lencx/ChatGPT#75]
it keeps asking to verify

![image](https://user-images.githubusercontent.com/45082271/209443266-488a7abc-2324-4f2c-bb9c-f28a966a918b.png)

**Comment by lencx** [comment]
This is the security policy of openai and cannot be avoided.

**Comment by jakedemian** [comment]
@lencx I am seeing a similar issue to OP, though I'm not sure it's the same issue.  I get asked to click the "Verify you are human" captcha, which I do, and then the application seems to restart and it asks to verify I'm human again.   Over and over, on repeat forever.  I don't see any error messages or anything, I just can't use the application because I keep getting asked to do the captcha.
